import { MongoClient, type Collection, type Db } from "mongodb";
import { env } from "../env.ts";

export type Track = "beginner" | "intermediate" | "advanced";
export const TRACKS: Track[] = ["beginner", "intermediate", "advanced"];

/** One document per signed-up user. `_id` is the user id used everywhere else. */
export type UserDoc = {
  _id: string;
  email: string;
  emailLower: string;
  // scrypt output, stored as `scrypt$<saltHex>$<hashHex>`. Never leaves the server.
  passwordHash: string;
  track: Track | null;
  placedAt: Date | null;
  placementScore: number | null;
  xp: number;
  tier: "free" | "pro";
  createdAt: Date;
};

export type ModuleProgressDoc = {
  _id: string;
  userId: string;
  moduleSlug: string;
  completedAt: Date;
  xpAwarded: number;
};

export type AttemptDoc = {
  _id: string;
  // Generated by the client when the quiz opens and replayed on every retry.
  // The unique index on it is what makes submission idempotent (invariant 7).
  attemptKey: string;
  userId: string;
  moduleSlug: string;
  submittedAt: Date;
  answers: Record<string, number | boolean | string>;
  objectiveScore: number;
  objectiveMax: number;
  // Kept so a re-grade never needs the client to resubmit.
  longAnswer: string;
  gradingStatus: "pending" | "graded" | "failed";
  longAnswerScore: number | null;
  longAnswerMax: number;
  longAnswerFeedback: string | null;
  xpAwarded: number;
};

export type WaitlistDoc = {
  _id: string;
  email: string;
  emailLower: string;
  createdAt: Date;
};

const client = new MongoClient(env.MONGODB_URI);
let connected: Promise<Db> | null = null;

/**
 * Connects on first use and reuses that one connection for the process. The
 * driver maintains its own pool, so a module-level client is correct here —
 * connecting per request would exhaust Atlas under any real load.
 */
export function db(): Promise<Db> {
  connected ??= client.connect().then(async (c) => {
    const database = c.db();
    await ensureIndexes(database);
    return database;
  });
  return connected;
}

export async function users(): Promise<Collection<UserDoc>> {
  return (await db()).collection<UserDoc>("users");
}
export async function moduleProgress(): Promise<Collection<ModuleProgressDoc>> {
  return (await db()).collection<ModuleProgressDoc>("module_progress");
}
export async function attempts(): Promise<Collection<AttemptDoc>> {
  return (await db()).collection<AttemptDoc>("quiz_attempts");
}
export async function waitlist(): Promise<Collection<WaitlistDoc>> {
  return (await db()).collection<WaitlistDoc>("waitlist");
}

// createIndex is idempotent, so this runs on every boot rather than needing a
// migration step. These are correctness constraints, not just performance:
// without them a replayed submission would award XP twice.
async function ensureIndexes(database: Db) {
  await Promise.all([
    database
      .collection("users")
      .createIndex({ emailLower: 1 }, { unique: true }),
    database
      .collection("quiz_attempts")
      .createIndex({ attemptKey: 1 }, { unique: true }),
    database
      .collection("quiz_attempts")
      .createIndex({ userId: 1, moduleSlug: 1 }),
    database
      .collection("quiz_attempts")
      .createIndex(
        { submittedAt: 1 },
        { partialFilterExpression: { gradingStatus: "pending" } },
      ),
    database
      .collection("module_progress")
      .createIndex({ userId: 1, moduleSlug: 1 }, { unique: true }),
    database
      .collection("waitlist")
      .createIndex({ emailLower: 1 }, { unique: true }),
  ]);
}

export async function closeDb() {
  await client.close();
  connected = null;
}
